port: "8080"

postgres:
  username: "postgres"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

redis:
  username: "default"
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
  host: "cache"
  port: "6379"
  dbnumber: 0
